---
title: "Risk_Project"
Author: Danny Zweben
date: "2024-05-29"

---

```{r}
df_filtered <- read.csv("/Users/dannyzweben/Desktop/CABLAB_Files/Psychonomics_2025/arsqdata/arsq-rawcode.csv")

```



##Scoring ARSQ
```{r}
arsq_prep_raw <- df_filtered %>% filter(redcap_event_name == "visit_1_y1_arm_1") %>% select(PID, starts_with("arsq_"))

arsq_prep_raw$arsq.score <- round(((arsq_prep_raw$arsq_familyconcern * arsq_prep_raw$arsq_familyexpect) + (arsq_prep_raw$arsq_friendconcern * arsq_prep_raw$arsq_friendexpect) + (arsq_prep_raw$arsq_protconcern * arsq_prep_raw$arsq_protexpect) +(arsq_prep_raw$arsq_supconcern * arsq_prep_raw$arsq_supexpect) + (arsq_prep_raw$arsq_soargueconcern * arsq_prep_raw$arsq_soargueexpect) + (arsq_prep_raw$arsq_occconcern * arsq_prep_raw$arsq_occexpect) + (arsq_prep_raw$arsq_partyconcern * arsq_prep_raw$arsq_partyexpect) + (arsq_prep_raw$arsq_distanceconcern * arsq_prep_raw$arsq_distanceexpect) + (arsq_prep_raw$arsq_talkconcern * arsq_prep_raw$arsq_talkexpect))/18,2)

arsq_total_score <- select(arsq_prep_raw, PID, arsq.score)



```

```{r}
# Load necessary package
library(dplyr)

# Assume your data frame is already loaded as arsq_total_score

# Force PID to numeric and filter for PID > 3000
arsq_total_score <- arsq_total_score %>%
  mutate(PID = as.numeric(PID)) %>%
  filter(PID > 3000)

# Z-score the ARSQ total score
arsq_total_score <- arsq_total_score %>%
  mutate(arsq_zscore = scale(arsq.score))

# Export to CSV
write.csv(
  arsq_total_score,
  "/Users/dannyzweben/Desktop/CABLAB_Files/Psychonomics_2025/arsqdata/arsq-rawcode_z.csv",
  row.names = FALSE
)


```

